print ('Введите название товара')
name = input (str())
print ('Введите стоимость товара')
price = input ()
print ('Введите вес товара')
weight = input ()
print ('Сколько у Вас денег?')
cash = input ()
summa = ( int(price) * int (weight))
print ( 'Чек', name , '-' , weight , 'кг -', price , 'руб/кг')
print ( 'Итого:', summa , 'руб.')
print ( 'Внесено:', cash , 'руб.')
print ( 'Сдача:' , int (cash) - int (summa) , 'руб.')